name: Convert OSM to PBF

on:
  workflow_dispatch:

jobs:
  convert:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Install Osmium Tool
        run: |
          sudo apt update
          sudo apt install -y osmium-tool

      - name: Prepare Input Directory
        run: mkdir -p data

      # Optional: Place your .osm file in /data or download it
      # Example of downloading your Overpass-exported .osm file:
      - name: Download OSM File
        run: |
          curl -L -o data/city.osm "https://your-download-url.com/city.osm"

      - name: Convert .osm to .osm.pbf
        run: |
          osmium convert data/city.osm -o data/city.osm.pbf

      - name: Commit Converted .osm.pbf
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@users.noreply.github.com"
          git add data/city.osm.pbf
          git commit -m "Add converted .osm.pbf file"
          git push
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
