name: Convert OSM to PBF

on:
  workflow_dispatch:

jobs:
  convert:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Install Osmium Tool
        run: |
          sudo apt update
          sudo apt install -y osmium-tool

      - name: Convert .osm to .osm.pbf
        run: |
          osmium convert raw/greater-bandung.osm -o raw/greater-bandung.osm.pbf

      - name: Commit Converted .osm.pbf
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@users.noreply.github.com"
          git add raw/greater-bandung.osm.pbf
          git commit -m "Add converted greater-bandung.osm.pbf"
          git push
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
