name: Update Route Data

on: workflow_dispatch

permissions:
  contents: write

jobs:
  fetch-routes:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          # Required to allow pushing changes back
          fetch-depth: 0

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install axios mkdirp

      - name: Run script
        run: node action-scripts/update-routes.js

      - name: Commit and push changes
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          
          # Add all changes in route-data/geojson directory
          git add route-data/geojson
          
          # Check if there are changes to commit
          if git diff-index --quiet HEAD --; then
            echo "No changes detected"
          else
            git commit -m "Automated update: Refreshed route data"
            git push
          fi
